### ISSUE TITLE
Improve validation for leap years

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#10]
29th of February should not be accepted on non-leap years

**Comment by kghbln** [comment]
To make this a bit more fun: Not every four years is a leap year. The rule is that if the year is divisible by 100 and not divisible by 400, leap year is skipped. The year 2000 was a leap year, for example, but the years 1700, 1800, and 1900 were not. The next time a leap year will be skipped is the year 2100.

**Comment by mzeinstra** [comment]
And only in the Gregorian calendar, the scope of this has not been discussed yet. However I assume that EDTF is only Gregorian based..
