### ISSUE TITLE
Support single digit notation for months/days?

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#25]
Currently `2000-1` is rejected while `2000-01` passes validation. Looking at https://www.loc.gov/standards/datetime/, the months and days are indeed always two digits. Do we need to support single digit notation?

**Comment by mzeinstra** [comment]
I would say no we do not want to support that, given that it outside the standard. 

It might be interesting for the community in the future to discuss this further imo.
