### ISSUE TITLE
Add French humanization

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#29]
Blocked on https://github.com/ProfessionalWiki/EDTF/issues/20

**Comment by JeroenDeDauw** [comment]
French strings will be provided by Claude

**Comment by mzeinstra** [comment]
@cnralux

**Comment by JeroenDeDauw** [comment]
French strings can be found at https://github.com/ProfessionalWiki/EDTF/blob/master/i18n/fr.json

You can find the English versions at https://github.com/ProfessionalWiki/EDTF/blob/master/i18n/en.json
