### ISSUE TITLE
Add support for ..1984 and 1670..1673

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#46]
These dates are currently supported:

* `[..1760-12-03]`
* `[..1984]`
* `{..1984}`
* `[1668,1670..1672]`

(see https://github.com/ProfessionalWiki/EDTF/blob/master/src/ExampleData/ValidEdtfStrings.php)

These ones are not

* `..1984`
* `1984..`
* `1670..1673`

(Note the lack of brackets)

**Comment by JeroenDeDauw** [comment]
@mzeinstra It would be good to know what these so far unsupported cases represent. Since they are not in the public spec (https://www.loc.gov/standards/datetime/) I can only guess:

* `..1984` is the same as `../1984`
* `1670..1673` is the same as `{1670..1673}` (all of 1670, 1671, 1672, 1673)

**Comment by cnralux** [comment]
@JeroenDeDauw After re-reading the ISO standard, I have to admit that I've overlooked the fact that the examples 1-4 only represent elements of SETs. As such, they are not valid without curly or square brackets. Sorry for the inconvenience.
