### ISSUE TITLE
Fix Seasons in Intervals

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/EDTF#52]
Provided that http://edtf.wikibase.wiki/ is up to date with this repo the humanisation of some dates with seasons is not working properly.

2005/2006-24 now humanises to '(2005 to 2006)' but expected '(2005 to Winter 2006)'
/1985-25 now humanises to '(From unknown to 1985)' but expected '((From unknown to Spring (Northern Hemisphere) 1985)'

see http://edtf.wikibase.wiki/wiki/Property:P1 for examples.

**Comment by JeroenDeDauw** [comment]
Demo wiki is not up to date. Should be fixed when we deploy new version later today.

**Comment by JeroenDeDauw** [comment]
Incorrect behavior visible at http://edtf.wikibase.wiki/wiki/Item:Q1
