### ISSUE TITLE
Humanisation is dealing with [.. strangely

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/EDTF#53]
Humanisation of lists containing .. are dealt with strangely. Three examples below.

1. In the case of
[..1990]
we get
(One of these: 1990)
But I expected
(One of these: 1990), or some earlier date

2. in the case of
[1984-10-10..1984-11-01]
we get
(One of these: 1984)
but I expected 
(one these: 1984-10-10 until 1984-11-01)
The loc.gov website writes them all out, but that can lead to unwanted behaviour imo.

3. in the case of
{ ..1983-12-31,1984-10-10..1984-11-01,1984-11-05..}
we get a list of all dates from 0-1983
All of these:
0
1
2
...
1983
1984
November 5th, 1984
but I expected
All of these (December 31st, 1983, October 10th, 1984 until November 1st, 1984, November 5th, 1984) and some earlier date, and some later date.

**Comment by JeroenDeDauw** [comment]
There are a few things going on here:
* `..` is not correctly handled for non-years, now tracked by https://github.com/ProfessionalWiki/EDTF/issues/55
* `{ ..1983-12-31,1984-10-10..1984-11-01,1984-11-05..}` contains a space. ` ..1983-12-31` is interpreted as `0..1983-12-31`. Does this need to change, and if so, how?
* The humanization currently does not support "open start" and "open end". Looks like I forgot about that. Tracked by https://github.com/ProfessionalWiki/EDTF/issues/56
* `[1000..1002]` internally gets turned into `1000`, `1001` and `1002`. This means we cannot show `One year bteween 1000 and 1002` without also changing the internal model. That is possible of course. My point is that the fix won't be trivial. So the question of importance/priority arises.

**Comment by mzeinstra** [comment]
1. Noted
2. Yes, spaces should either be trimmed or decided to be invalid. What would you prefer?
3. Noted
4. low priority, probably best to just show them all. I don't expect that we will run into a barrier of thousands of years soon. But let's note this as a possible known issue

**Comment by JeroenDeDauw** [comment]
> Yes, spaces should either be trimmed or decided to be invalid. What would you prefer?

Trim. It is quite natural to write something like `[2020, 2021, 2022]`. https://github.com/ProfessionalWiki/EDTF/issues/59

> But let's note this as a possible known issue

https://github.com/ProfessionalWiki/EDTF/issues/58
