### ISSUE TITLE
Are negative number correctly humanised

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/EDTF#54]
should -1 be humanised to
2 BC or to 1 BC

And is 0 actually
1 BC?

See https://en.wikipedia.org/wiki/Year_zero#ISO_8601

Let's first get agreement on this, before changing code

@cnralux how should -1 one be represented?

**Comment by JeroenDeDauw** [comment]
Standard Wikibase time value appear to differentiate between 0 and -1: https://cat-collective2.wiki.opencura.com/wiki/Property:P1

**Comment by mzeinstra** [comment]
And we have heard that the ISO standard also accepts 0 as a year. Closing this remark.
