### ISSUE TITLE
Fix humanization of set dates with open start or end

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#56]
Humanization currently does not hold into account open start or end for dates in sets. This leads to incorrect humanization.

https://github.com/ProfessionalWiki/EDTF/commit/76b40810aa5860dc4f59646097fd28217a31b4d2#diff-0347697c618b3c672f42dd31dc4d3858bc40b972bc18a2086cbb1270faacdbc4R98-R99

Desired behavior:
* `[..2020-21]` -> `Spring 2020 or earlier`
* `[2020-21..]` -> `Spring 2020 or later`
* `{..2020-21}` -> `Spring 2020 and earlier`
* `{2020-21..}` -> `Spring 2020 and later`

**Comment by JeroenDeDauw** [comment]
@mzeinstra @cnralux this ticket is about fixing humanization of dates like `{..2020}`. While working on that, @chaudbak has raised the question if we should also support dates like `{..2020, 2025, 2026}`. Or should those not get through validation in the first place? The public spec (https://www.loc.gov/standards/datetime/) does not contain any such dates.

**Comment by mzeinstra** [comment]
Very good question. I would suggest that this is not high priority and that we document this as an open question with the current functionality. Would that work for you?

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/ProfessionalWiki/EDTF/pull/63
