### ISSUE TITLE
Humanizer for sets returning blank responses

### ISSUE THREAD

**Issue by seth-shaw-unlv** [ProfessionalWiki/EDTF#65]
I started testing this library today as a potential replacement for some of my own EDTF parsing and formatting. So far, so good. I was able to get 1.2.0 using composer, but when I attempted to humanize a set it returned a blank response:

```
Psy Shell v0.10.8 (PHP 7.4.13 — cli) by Justin Hileman
Drush Site-Install (Drupal 8.9.14)
>>> $humanizer = \EDTF\EdtfFactory::newHumanizerForLanguage( 'en' );
=> EDTF\PackagePrivate\Humanizer\InternationalizedHumanizer {#4250}
>>> $parser = \EDTF\EdtfFactory::newParser();
=> EDTF\PackagePrivate\SaneParser {#4066}
>>> $parsingResult = $parser->parse('{2020-01..2020-03}');
=> EDTF\ParsingResult {#4094}
>>> $parsingResult->isValid();
=> true
>>> $parsingResult->getInput();
=> "{2020-01..2020-03}"
>>> $humanizer->humanize($parsingResult->getEdtfValue());
=> ""
```

Everything other than sets humanize fine.

**Comment by mzeinstra** [comment]
I believe this is an issue that relates to #46 

My own instance of a WIkibase with based on this does show proper humanisation of that string though (based on https://github.com/ProfessionalWiki/WikibaseEdtf )

![image](https://user-images.githubusercontent.com/5627431/115677219-8e987780-a350-11eb-8012-645bbbafcdab.png)

**Comment by JeroenDeDauw** [comment]
This is expected behavior actually, but clearly the docs can use some improving.

The `Humanizer` service does not support sets. For sets you need the `StructuredHumanizer`. This is because for sets it is often not possible to make a single string that represents the date in a readable manner, since dates can contain things such as commas.

**Comment by JeroenDeDauw** [comment]
So in other words, if you want support for sets, just use `StructuredHumanizer` (for all values), instead of using `Humanizer`.

**Comment by JeroenDeDauw** [comment]
Here is an example of a set shown on multiple lines: 
![image](https://user-images.githubusercontent.com/146040/115726836-60805b00-a383-11eb-84db-6ed7f99ad992.png)

**Comment by seth-shaw-unlv** [comment]
Thanks. Using the structured humanizer did the trick:
```
>>> $humanizer = \EDTF\EdtfFactory::newStructuredHumanizerForLanguage("en");
=> EDTF\PackagePrivate\Humanizer\PrivateStructuredHumanizer {#4297}
>>> $parser = \EDTF\EdtfFactory::newParser();
=> EDTF\PackagePrivate\SaneParser {#4300}
>>> $parsingResult = $parser->parse('{2020-01..2020-03}');
=> EDTF\ParsingResult {#4308}
>>> $humanizer->humanize($parsingResult->getEdtfValue());
=> EDTF\HumanizationResult {#4305}
>>> $result = $humanizer->humanize($parsingResult->getEdtfValue());
=> EDTF\HumanizationResult {#4320}
>>> $result->getSimpleHumanization();
=> "All of these: January 2020, February 2020, March 2020"
```
