### ISSUE TITLE
When date only holds a year no humanised form is presented.

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/EDTF#75]
Compare date of birth and date of death.

<img width="383" alt="Screenshot 2021-12-17 at 13 26 43" src="https://user-images.githubusercontent.com/5627431/146544595-4d2154d3-4dd6-4a3f-839f-100281b4791f.png">

**Comment by JeroenDeDauw** [comment]
Yeah that is on purpose. Looks weird and confusing if you have

1984
(1984)

**Comment by mzeinstra** [comment]
Ok thanks for clarifying, closing ticket.
