### ISSUE TITLE
Translation issue with message [[MediaWiki:Edtf-day-and-year/en]]

### ISSUE THREAD

**Issue by verdy-p** [ProfessionalWiki/EDTF#76]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=edtf-day-and-year&group=mwgithub-edtf&language=fr

This message requires using an ordinal for the day in various languages. But the form of the ordinal is depending on the value of the day number.

Can we use a {{PLURAL:$1|er|e}} for example in French (because "1e jour" is incorrect in French and must be "1er jour", but we need "2e jour" for all other days of the month).

Also some language will format the ordinal differently with more complex rules than just with a simple PLURAL.  Just consider English: "day 1 of an unknown month" is very unnatural. I would prefer "1st day of an unknown month", with complex ordinals: "1st", "2nd", "4rd", "5th"...20th", "21st", "22nd", "23rd", "24th"..."30th", "31st".  Same case in German (if we don't use ordinals), but no problem wit the notation with dot ("1." ... "31.") as it uses the same suffix ("."). No problem in Italian, Portuguese or Spanish using the ("o") suffix (or the ordinal superscript "o" in Spanish), or in Japanese/Chinese (using the same ideogram meaning "day" suffixed to the number

**Comment by JeroenDeDauw** [comment]
Short answer: not possible. No `PLURAL`.

I had to [create something from scratch to support TranslateWiki](https://github.com/ProfessionalWiki/EDTF/tree/master/src/PackagePrivate/Humanizer/Internationalization) at all in this PHP library. That implementation only supports $ replacement, it does not have the PLURAL function and other utilities like you have in MediaWiki.

**Comment by verdy-p** [comment]
Strange: EDTF is suppsoed to handle date formats for all languages.

Date formats using ordinals, or sometimes not using Western Arabic digits at all (notably Arabic, Farsi/Urdu, and most Indic languages, or dates in Latin using Roman numbers) are not uncommon.

So that's still something to be developped.

**Comment by verdy-p** [comment]
As well there does not seem to exist any support for calendars other than Gregorian, even the simplest ones like modern Thai and Japanese (even if they have more eras), or more complex ones like Julian or the former French Republican (both not aligned with Gregorian), and lunar or lunisolar calendars (like Semitic calendars)

**Comment by JeroenDeDauw** [comment]
Contributions are welcome

**Comment by mzeinstra** [comment]
I labelled this issue as a question and potential enhancement. 

I made an issue (#77) that restates this question as a future feature. Closing this issue to make the discussion on this more concrete at #77.
