### ISSUE TITLE
Translation issue with message MediaWiki:Edtf-and/fi

### ISSUE THREAD

**Issue by Nikerabbit** [ProfessionalWiki/EDTF#86]
MediaWiki messages cannot contain trailing whitespace, it's stripped on save.

URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=edtf-and&group=mwgithub-edtf&language=fi

**Comment by JeroenDeDauw** [comment]
Already fixed by https://github.com/ProfessionalWiki/EDTF/pull/85/files, which still needs to be merged though

**Comment by JeroenDeDauw** [comment]
Ah what the hell, I just merged it now to avoid translation pains.
