### ISSUE TITLE
Add handling of sets

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/EDTF#9]
See "Set representation" under level 2 https://www.loc.gov/standards/datetime/

See ValidEdtfStrings.php for commented out test cases that should pass but currently do not

**Comment by mzeinstra** [comment]
Updated a string on ValidEdtfStrings.php. Needs rechecking.

**Comment by JeroenDeDauw** [comment]
The "All Members" sets (curly brackets) have implementation priority over "One of a set" cases (square brackets)

**Comment by JeroenDeDauw** [comment]
Pseudocode by @mzeinstra 

```
But I assume if you can validate one than you can validate all of them. 

e.g in pseudocode:

if string.first == '{' and string.last == '}'
  for each s as string.explode(,)
    if not EDTF_Valid(s) 
      return false
  return true

You might need a count that each list contains at least one or two elements.
```
